
MASON = "application/vnd.mason+json"
APIARY_URL = "https://workoutlogapi.docs.apiary.io/#reference/"
LINK_RELATIONS_URL = "/workoutlog/link-relations/"
ERROR_PROFILE = "/profiles/error/"
WORKOUT_PROFILE = "/profiles/workout/"
EXERCISE_PROFILE = "/profiles/exercise/"
MAX_DATA_PROFILE = "/profiles/max-data/"
SET_PROFILE = "/profiles/set/"
WEEKLY_PROGRAMMING_PROFILE = "/profiles/weekly-programming/"